CREATE TABLE mynewdb.TB_RANKING (
  `CATEGORY` varchar(20) DEFAULT NULL,
  `ITEM_NAME` varchar(200) DEFAULT NULL,
  `RANKING` int(3) DEFAULT NULL,
  `HYPERLINK` varchar(500) DEFAULT NULL,
  `UPDATE_DATE` date DEFAULT NULL);
